sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IKJdHOw9S4lWwuOZfNdqSBPSIP4ZInDZjku/GQ6aYYJrXgV8xkFDaaauihhV1c5ImQy3upt7097i99b0Zoi/Fblp9ZJo7BGZOSoHqO7Cdb3TskVM4d+/ICx1XDRV6XaHZ1wiKQ9ot8xrTfSNtsa5A3rtoztg0lMDq4wf/8LwaubweKxOiexVl4SKLf97e84ygXPRgkVXpOA35XBCRrB9tBUE9QLhX3R2ZufhjfKqFs1tvg/2nF9kgBj6t/rokuLYB+P7vzCrmaBpr6ci53dpLFCmjvHHpl56+fO3jS4P+DT+uFw/zjSc6d3bYo4V07oolbSO4SjcKFMVfr3xUmKcI6/FWsEROUMIPZtUpuHaLgA5GCEw9PlLdiFP7V+S08YZzV+VFoA+/jRR4A5nEhpZKTOztvX7qvKoAQnJGnn3mheEGnZTXqobWRtF+rhlJOlGcUZd3w76MvDYtuWZ2TeB3ym54/k6Gka2aWYTbH4b9a7QanKtCieIjckO6Vs7nHIqH9n3fyjdUmMaMcQf0o0aIMziLO8CxQnSlrJ9beCg2Ak4aNA1n45XRCwGDa9FtRhefx4XeuI4uP4UB7hpvO0V6zpDWJnUgotJswD/Z3Ig+Tbg3K2d9pxHhOSSV22YvNshb/rQqEVMzEvIUo5Nbnc+GQCn+lYeV3VeubOe01mqd/A=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Town-and-Country-Or-Life-at-Home-and-Abroad-Without-and-Within-Us_4669
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy